paths:
  PATH_1_0:
    - {x: 0.425, y: 1.0, yaw: 0.0, v: 0.5}


  PATH_1_1:
    - {x: 3.0, y: 1.0, yaw: 0.0, v: 0.5}
    - {x: 3.0, y: 3.0, yaw: 0.7854, v: 0.5}
    - {x: 3.0, y: 3.0, yaw: 1.5708, v: 0.2}

  PATH_2_0:
    - {x: 3.0, y: 1.0, yaw: 0.0, v: 0.4}

  PATH_2_1:
    - {x: 3.0, y: 2.0, yaw: 0.0, v: 0.4}
    - {x: 3.0, y: 4.0, yaw: 0.0, v: 0.7}

  PATH_3_0:
    - {x: 3.0, y: 5.0, yaw: 1.57, v: 0.4}
  
  PATH_3_1:
    - {x: 4.0, y: 7.0, yaw: 0.0, v: 0.7}
    - {x: 4.0, y: 8.0, yaw: 0.0, v: 0.2}

  PATH_3_2:
    - {x: 3.0, y: 6.0, yaw: 0.0, v: 0.8}
    - {x: 3.0, y: 8.0, yaw: 0.0, v: 0.2}

  PATH_4f_0:
    - {x: 5.0, y: 7.0, yaw: 0.0, v: 0.4}

  PATH_4f_1:
    - {x: 6.0, y: 7.0, yaw: 0.758, v: 0.4}
    - {x: 6.0, y: 8.0, yaw: 1.57, v: 0.2}

  PATH_4f_2:
    - {x: 8.0, y: 7.0, yaw: 0.0, v: 0.4}

  PATH_4b_0:
    - {x: 7.5, y: 8.0, yaw: -1.57, v: 0.4}

  PATH_4b_1:
    - {x: 7.5, y: 2.0, yaw: -1.57, v: 1.0}

  PATH_4b_2:
    - {x: 6.0, y: 2.0, yaw: -3.14, v: 0.4}
    - {x: 6.0, y: 6.0, yaw: 1.57, v: 0.2}